app.factory('moviesFactory', function () {

var movies = [
  {
    "Price":5,
  "Title": "Star Wars: Episode IV - A New Hope",
  "Year": "1977",
  "Rated": "PG",
  "Released": "25 May 1977",
  "Runtime": "121 min",
  "Genre": "Action, Adventure, Fantasy",
  "Director": "George Lucas",
  "Writer": "George Lucas",
  "Actors": "Mark Hamill, Harrison Ford, Carrie Fisher, Peter Cushing",
  "Plot": "Luke Skywalker joins forces with a Jedi Knight, a cocky pilot, a wookiee and two droids to save the galaxy from the Empire's world-destroying battle-station, while also attempting to rescue Princess Leia from the evil Darth Vader.",
  "Language": "English",
  "Country": "USA",
  "Awards": "Won 6 Oscars. Another 48 wins & 28 nominations.",
  "Poster": "https://images-na.ssl-images-amazon.com/images/M/MV5BZGEzZTExMDEtNjg4OC00NjQxLTk5NTUtNjRkNjA3MmYwZjg1XkEyXkFqcGdeQXVyMTQxNzMzNDI@._V1_SX300.jpg",
  "Metascore": "92",
  "imdbRating": "8.7",
  "imdbVotes": "955,091",
  "imdbID": "tt0076759",
  "Type": "movie",
  "Response": "True"
},

{
  "Price":5,
"Title": "The Goonies",
"Year": "1985",
"Rated": "PG",
"Released": "07 Jun 1985",
"Runtime": "114 min",
"Genre": "Adventure, Comedy, Family",
"Director": "Richard Donner",
"Writer": "Steven Spielberg (story), Chris Columbus (screenplay)",
"Actors": "Sean Astin, Josh Brolin, Jeff Cohen, Corey Feldman",
"Plot": "In order to save their home from foreclosure, a group of misfits set out to find a pirate's ancient valuable treasure.",
"Language": "English, Spanish, Cantonese, Italian",
"Country": "USA",
"Awards": "2 wins & 6 nominations.",
"Poster": "https://images-na.ssl-images-amazon.com/images/M/MV5BOTlmMWU5YTQtOWMxMi00OWE0LTg2MDItMjEyZDBjNWY0NDdhL2ltYWdlXkEyXkFqcGdeQXVyNTAyODkwOQ@@._V1_SX300.jpg",
"Metascore": "60",
"imdbRating": "7.8",
"imdbVotes": "185,900",
"imdbID": "tt0089218",
"Type": "movie",
"Response": "True"
},
{
  "Price":5,
"Title": "Christine",
"Year": "1983",
"Rated": "R",
"Released": "09 Dec 1983",
"Runtime": "110 min",
"Genre": "Horror",
"Director": "John Carpenter",
"Writer": "Stephen King (novel), Bill Phillips (screenplay)",
"Actors": "Keith Gordon, John Stockwell, Alexandra Paul, Robert Prosky",
"Plot": "A nerdish boy buys a strange car with an evil mind of its own and his nature starts to change to reflect it.",
"Language": "English",
"Country": "USA",
"Awards": "2 nominations.",
"Poster": "https://images-na.ssl-images-amazon.com/images/M/MV5BZThhNDQxNzAtOTYzZC00MzZkLWI2YjItOTE2ZjliZDY3NTFkXkEyXkFqcGdeQXVyMTQxNzMzNDI@._V1_SX300.jpg",
"Metascore": "N/A",
"imdbRating": "6.6",
"imdbVotes": "52,428",
"imdbID": "tt0085333",
"Type": "movie",
"Response": "True"
},
{
  "Price":5,
"Title": "Back to the Future",
"Year": "1985",
"Rated": "PG",
"Released": "03 Jul 1985",
"Runtime": "116 min",
"Genre": "Adventure, Comedy, Sci-Fi",
"Director": "Robert Zemeckis",
"Writer": "Robert Zemeckis, Bob Gale",
"Actors": "Michael J. Fox, Christopher Lloyd, Lea Thompson, Crispin Glover",
"Plot": "Marty McFly, a 17-year-old high school student, is accidentally sent 30 years into the past in a time-traveling DeLorean invented by his close friend, the maverick scientist Doc Brown.",
"Language": "English",
"Country": "USA",
"Awards": "Won 1 Oscar. Another 18 wins & 26 nominations.",
"Poster": "https://images-na.ssl-images-amazon.com/images/M/MV5BZmU0M2Y1OGUtZjIxNi00ZjBkLTg1MjgtOWIyNThiZWIwYjRiXkEyXkFqcGdeQXVyMTQxNzMzNDI@._V1_SX300.jpg",
"Metascore": "86",
"imdbRating": "8.5",
"imdbVotes": "773,599",
"imdbID": "tt0088763",
"Type": "movie",
"Response": "True"
},
{
  "Price":5,
"Title": "Star Wars: Episode V - The Empire Strikes Back",
"Year": "1980",
"Rated": "PG",
"Released": "20 Jun 1980",
"Runtime": "124 min",
"Genre": "Action, Adventure, Fantasy",
"Director": "Irvin Kershner",
"Writer": "Leigh Brackett (screenplay), Lawrence Kasdan (screenplay), George Lucas (story by)",
"Actors": "Mark Hamill, Harrison Ford, Carrie Fisher, Billy Dee Williams",
"Plot": "After the rebels have been brutally overpowered by the Empire on their newly established base, Luke Skywalker takes advanced Jedi training with Master Yoda, while his friends are pursued by Darth Vader as part of his plan to capture Luke.",
"Language": "English",
"Country": "USA",
"Awards": "Won 1 Oscar. Another 19 wins & 18 nominations.",
"Poster": "https://images-na.ssl-images-amazon.com/images/M/MV5BYmViY2M2MTYtY2MzOS00YjQ1LWIzYmEtOTBiNjhlMGM0NjZjXkEyXkFqcGdeQXVyNDYyMDk5MTU@._V1_SX300.jpg",
"Metascore": "81",
"imdbRating": "8.8",
"imdbVotes": "882,240",
"imdbID": "tt0080684",
"Type": "movie",
"Response": "True"
},
{
  "Price":5,
"Title": "Contact",
"Year": "1997",
"Rated": "PG",
"Released": "11 Jul 1997",
"Runtime": "150 min",
"Genre": "Drama, Mystery, Sci-Fi",
"Director": "Robert Zemeckis",
"Writer": "James V. Hart (screenplay), Michael Goldenberg (screenplay), Carl Sagan (based on the novel by), Carl Sagan (based on the story by), Ann Druyan (based on the story by)",
"Actors": "Jena Malone, David Morse, Jodie Foster, Geoffrey Blake",
"Plot": "Dr. Ellie Arroway, after years of searching, finds conclusive radio proof of intelligent aliens, who send plans for a mysterious machine.",
"Language": "English, Spanish, German, Russian",
"Country": "USA",
"Awards": "Nominated for 1 Oscar. Another 14 wins & 26 nominations.",
"Poster": "https://images-na.ssl-images-amazon.com/images/M/MV5BYWNkYmFiZjUtYmI3Ni00NzIwLTkxZjktN2ZkMjdhMzlkMDc3XkEyXkFqcGdeQXVyNDk3NzU2MTQ@._V1_SX300.jpg",
"Metascore": "62",
"imdbRating": "7.4",
"imdbVotes": "208,129",
"imdbID": "tt0118884",
"Type": "movie",
"Response": "True"
},
{
  "Price":5,
"Title": "Toy Story",
"Year": "1995",
"Rated": "G",
"Released": "22 Nov 1995",
"Runtime": "81 min",
"Genre": "Animation, Adventure, Comedy",
"Director": "John Lasseter",
"Writer": "John Lasseter (original story by), Pete Docter (original story by), Andrew Stanton (original story by), Joe Ranft (original story by), Joss Whedon (screenplay), Andrew Stanton (screenplay), Joel Cohen (screenplay), Alec Sokolow (screenplay)",
"Actors": "Tom Hanks, Tim Allen, Don Rickles, Jim Varney",
"Plot": "A cowboy doll is profoundly threatened and jealous when a new spaceman figure supplants him as top toy in a boy's room.",
"Language": "English",
"Country": "USA",
"Awards": "Nominated for 3 Oscars. Another 23 wins & 18 nominations.",
"Poster": "https://images-na.ssl-images-amazon.com/images/M/MV5BMDU2ZWJlMjktMTRhMy00ZTA5LWEzNDgtYmNmZTEwZTViZWJkXkEyXkFqcGdeQXVyNDQ2OTk4MzI@._V1_SX300.jpg",
"Metascore": "95",
"imdbRating": "8.3",
"imdbVotes": "659,999",
"imdbID": "tt0114709",
"Type": "movie",
"Response": "True"
}




  ];

return { movies:movies
  };

});
